version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  groups:
    pip-version:
      applies-to: version-updates
      patterns:
      - '*'
    pip-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  groups:
    github-actions-version:
      applies-to: version-updates
      patterns:
      - '*'
    github-actions-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  groups:
    docker-version:
      applies-to: version-updates
      patterns:
      - '*'
    docker-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: terraform
  directory: /
  schedule:
    interval: daily
  groups:
    terraform-version:
      applies-to: version-updates
      patterns:
      - '*'
    terraform-security:
      applies-to: security-updates
      patterns:
      - '*'
